from std.collections import InlineArray

trait DistanceComputerTrait(Movable, Deinitable):
    def distance(self, id: Int, threshold: Float32 = Float32.MAX) -> Float32: ...
    def distance_batch4(self, id0: Int, id1: Int, id2: Int, id3: Int) -> InlineArray[Float32, 4]: ...
    def symmetric_distance(self, i: Int, j: Int) -> Float32: ...
    def prefetch_vector(self, id: Int): ...
    def is_exact(self) -> Bool: ...

trait StorageTrait(Movable, Deinitable):
    comptime ComputerType: DistanceComputerTrait
    comptime HNSW_PTHREAD_STORAGE_KIND: Int = -1
    def get_distance_computer(self, query: Pointer[Float32, _]) -> Self.ComputerType: ...
    def add(mut self, x: Span[Float32, _]): ...
    def get_vector(self, id: Int) -> Pointer[Float32, MutUntrackedOrigin]: ...
